-- Types

local SOUND_KIND = {
	REGULAR = "breath",
	HEALTH_RELATED = "health",
	STAMINA_RELATED = "run",
	PSY_RELATED = "psy",
	WEATHER_RAIN = "weather_rain"
}

local SOUND_REGULAR_MODE = {
	REGULAR = "1",
	ANXIOUS = "2",
	DISTRESSED = "3",
	TERRIFIED = "4",
	SWEETENER = "s"
}

local SOUND_HEALTH_RELATED_MODE = {
	WOUNDED = "1",
	SWEETENER = "s"
}

local SOUND_STAMINA_RELATED_MODE = {
	ACTIVE = "1",
	EXHAUSTED = "2"
}

local SOUND_PSY_RELATED_MODE = {
	HALLUCINATING = "1",
	BLACKING_OUT = "2"
}

local SOUND_WEATHER_RAIN_MODE = {
	SWEETENER = "s"
}

-- Sound Configuration

local NUM_SOUNDS_BY_KIND_AND_MODE = {
	[SOUND_KIND.REGULAR] = {
		[SOUND_REGULAR_MODE.REGULAR] = 12,
		[SOUND_REGULAR_MODE.ANXIOUS] = 12,
		[SOUND_REGULAR_MODE.DISTRESSED] = 12,
		[SOUND_REGULAR_MODE.TERRIFIED] = 12,
		[SOUND_REGULAR_MODE.SWEETENER] = 8
	},
	[SOUND_KIND.HEALTH_RELATED] = {
		[SOUND_HEALTH_RELATED_MODE.WOUNDED] = 10,
		[SOUND_HEALTH_RELATED_MODE.SWEETENER] = 10
	},
	[SOUND_KIND.STAMINA_RELATED] = {
		[SOUND_STAMINA_RELATED_MODE.ACTIVE] = 12,
		[SOUND_STAMINA_RELATED_MODE.EXHAUSTED] = 14
	},
	[SOUND_KIND.PSY_RELATED] = {
		[SOUND_PSY_RELATED_MODE.HALLUCINATING] = 4,
		[SOUND_PSY_RELATED_MODE.BLACKING_OUT] = 1
	},
	[SOUND_KIND.WEATHER_RAIN] = {
		[SOUND_WEATHER_RAIN_MODE.SWEETENER] = 10
	}
}

-- Sound Pause Factors

local SOUND_PAUSE_FACTOR_BY_KIND_AND_MODE = {
	[SOUND_KIND.REGULAR] = {
		[SOUND_REGULAR_MODE.REGULAR] = 1.4,
		[SOUND_REGULAR_MODE.ANXIOUS] = 1.3,
		[SOUND_REGULAR_MODE.DISTRESSED] = 1.2,
		[SOUND_REGULAR_MODE.TERRIFIED] = 1.2,
		[SOUND_REGULAR_MODE.SWEETENER] = 1.2
	},
	[SOUND_KIND.HEALTH_RELATED] = {
		[SOUND_HEALTH_RELATED_MODE.WOUNDED] = 1.3,
		[SOUND_HEALTH_RELATED_MODE.SWEETENER] = 1.2
	},
	[SOUND_KIND.STAMINA_RELATED] = {
		[SOUND_STAMINA_RELATED_MODE.ACTIVE] = 1.3,
		[SOUND_STAMINA_RELATED_MODE.EXHAUSTED] = 1.2
	},
	[SOUND_KIND.PSY_RELATED] = {
		[SOUND_PSY_RELATED_MODE.HALLUCINATING] = 2.0,
		[SOUND_PSY_RELATED_MODE.BLACKING_OUT] = 2.0
	},
	[SOUND_KIND.WEATHER_RAIN] = {
		[SOUND_WEATHER_RAIN_MODE.SWEETENER] = 2.0
	}
}

-- Weathers

local WEATHER_KIND = {
	CLEAR = "clear",
	PARTLY_CLOUDY = "partly",
	CLOUDY = "cloudy",
	FOGGY = "foggy",
	RAINING = "rain",
	STORM = "storm"
}

-- Interaction

local SOUND_SUSPENSION_REASON = {
	REGULAR = "regular",
	ACTION = "action",
}

local HIT_KIND = {
	PHYSICAL = "physical",
	PSYCHIC = "psychic"
}

local ITEM_USE_COOLDOWN_BY_KIND = {
	["i_tobacco"] = 11000,
	["i_drink"] = 11000,
	["i_food"] = 8000,
	["i_medical"] = 10000,
	["i_bandage"] = 5000,
	["o_helmet"] = 5500
}

local UNDERGROUND_LEVELS = {
	["jupiter_underground"] = true,
	["l03u_agr_underground"] = true,
	["l04u_labx18"] = true,
	["l08u_brainlab"] = true,
	["l10u_bunker"] = true,
	["l12u_control_monolith"] = true,
	["l12u_sarcofag"] = true,
	["l13u_warlab"] = true,
	["labx8"] = true,
}

-- State

opt = {}

local sound_cooldown_time = 0

local last_actor_speed = 0
local last_actor_position = { x = 0, y = 0, z = 0 }
local last_actor_speed_time = 0
local last_actor_hit_time = 0
local last_actor_hit_kind = nil
local last_actor_fear = 0

local sound_action_cooldown_time = 0

local sound_object_ref = nil
local extra_sound_object_ref = nil

local sound_index_by_kind_and_mode = {}

-- Residuality means a mode is retained for some time after the condition is no longer met.
-- A given kind and mode are kept until the associated cooldown is hit.
-- Can add forced state transitions where a mode always has to be cycled back up.

-- Format for values: `{ mode = nil, pause_factor = 0, time = 0 }`
local sound_residual_cooldown_by_kind = {}

-- Init

function init_options()
	opt.debug_mode = true

	opt.speed = {}

	local ini_eff = ini_file("plugins\\actor_effects.ltx")
	local settings_speed = ini_eff:line_count("settings_speed")

	for i = 0, settings_speed - 1 do
		local _, id, value = ini_eff:r_line_ex("settings_speed", i, "", "")

		if id and value then
			opt.speed[id] = tonumber(value)
		end
	end

	opt.health = {
		injury_snd = nil,
		level1 = ini_eff:r_float_ex("settings_health", "level1"),
		level2 = ini_eff:r_float_ex("settings_health", "level2")
	}

	opt.cam_dist = ini_eff:r_float_ex("settings", "cam_dist") or 4

	opt.speaking_cooldown = 2500
	opt.speaking_sound_volume = 1.75

	opt.extra_sound_volume = 0.5

	opt.body_noises_default_sound_volume = 0.6

	opt.item_use_cooldown = 2500
	opt.hit_distress_cooldown = 20000
	opt.residuality_time = 12000
	opt.fear_factor_npc_detection_radius = 40

	opt.breathing_sound_volume = 0.4
	opt.breathing_sound_volume_jitter = 0.075
	opt.breathing_sound_pitch_jitter = 0.065

	opt.masked_breathing_sound_coeff = 1.25

	opt.enable_breathing_sound = ui_options.get("sound/environment/breathing_sound")
end

-- Actor Value Updates

function update_actor_cam_distance(actor)
	last_cam_dist = actor:bone_position("bip01_head"):distance_to_sqr(device().cam_pos)
end

function update_actor_speed(actor)
	local current_position = actor:position()
	local current_speed = (current_position.x - last_actor_position.x) ^ 2 +
		(current_position.y - last_actor_position.y) ^ 2 + (current_position.z - last_actor_position.z) ^ 2

	last_actor_position.x = current_position.x
	last_actor_position.y = current_position.y
	last_actor_position.z = current_position.z

	last_actor_speed = current_speed
end

function update_actor_speed_time()
	if (last_actor_speed > opt.speed.mini) then
		last_actor_speed_time = clamp(last_actor_speed_time + opt.speed.inc, 0, 30)
	else
		last_actor_speed_time = clamp(last_actor_speed_time - opt.speed.dec, 0, 30)
	end
end

-- Ticking

function tick_all_sound_indices()
	-- Tick all so breathing cycle is consistent between all kinds and modes.

	for kind, _ in pairs(NUM_SOUNDS_BY_KIND_AND_MODE) do
		if sound_index_by_kind_and_mode[kind] == nil then
			sound_index_by_kind_and_mode[kind] = {}
		end

		for mode, _ in pairs(NUM_SOUNDS_BY_KIND_AND_MODE[kind]) do
			local current_index = sound_index_by_kind_and_mode[kind][mode] or 0
			local num_sounds = NUM_SOUNDS_BY_KIND_AND_MODE[kind][mode]
			local updated_index = current_index % num_sounds + 1

			sound_index_by_kind_and_mode[kind][mode] = updated_index
		end
	end
end

function get_sound_index(kind, mode)
	if not sound_index_by_kind_and_mode[kind] then
		return nil
	end

	return sound_index_by_kind_and_mode[kind][mode]
end

function random_sound_index(kind, mode)
	-- Allow random index picks for extra sounds (outside of breathing cycle).
	local num_sounds = NUM_SOUNDS_BY_KIND_AND_MODE[kind][mode] or 1
	return math.random(1, num_sounds)
end

-- Factors

function get_pause_factor(kind, mode)
	return SOUND_PAUSE_FACTOR_BY_KIND_AND_MODE[kind][mode]
end

-- Cycle

function update_breathing(actor)
	if (not opt.enable_breathing_sound) then
		return
	end

	update_actor_cam_distance(actor)
	update_actor_speed(actor)
	update_actor_speed_time()

	handle_breathing_cycle(actor)
end

function did_exceed_cooldowns()
	return did_exceed_breathing_cooldown() and did_exceed_action_cooldown()
end

function did_exceed_breathing_cooldown()
	return time_global() > sound_cooldown_time
end

function did_exceed_action_cooldown()
	return time_global() > sound_action_cooldown_time
end

-- Actor Breathing

function handle_breathing_cycle(actor)
	local time = time_global()
	local health = actor.health
	local psy_health = get_psy_health()
	local stamina = actor.power
	local time_since_last_hit = time - last_actor_hit_time

	-- Check player alive state and cooldowns

	if not did_exceed_cooldowns() or (health <= 0) then
		return
	end

	-- Tick Breathing Cycles

	tick_all_sound_indices()

	-- Player Conditions

	local fear_factor = calculate_fear_factor()

	-- Residuals

	-- If fear is high, health is low, or stamina is low, clear residual sound
	if fear_factor > 0.9 or health < 0.25 or stamina < 0.2 then
		log("Clearing all residual sounds, extreme circumstances (fear factor: " .. fear_factor .. ", health: " ..
			health .. ", stamina: " .. stamina .. ").")
		sound_residual_cooldown_by_kind = {}
	end

	for sound_kind, sound_record in pairs(sound_residual_cooldown_by_kind) do
		do
			if not sound_record or not sound_record.mode then
				goto continue
			end

			local sound_mode = sound_record.mode

			if time >= sound_record.time then
				-- Residual time window exceeded, clear record.
				sound_residual_cooldown_by_kind[sound_kind] = nil

				log("Clearing residual sound of kind '" ..
					sound_kind ..
					"' with mode " .. sound_record.mode .. " (expired since " .. time - sound_record.time .. "ms).")

				return
			end

			-- Residual time window hit, use and play from record.
			play_sound_with_parameters(actor, sound_kind, sound_mode, false)

			log("Playing residual sound of kind '" .. sound_kind .. "' with mode " .. sound_record.mode
				.. " (expiration in " .. sound_record.time - time .. "ms).")
			return
		end

		::continue::
	end

	-- Low Health

	if health < 0.25 then
		if math.random() < 0.35 then
			-- Player is critically wounded, play sweetener.
			log("Playing low health sweetener sound with health " .. health .. ".")
			play_sound_sweetener_with_parameters(actor, SOUND_KIND.HEALTH_RELATED, SOUND_HEALTH_RELATED_MODE.SWEETENER)
			return
		end

		log("Playing low health breathing sound with health " .. health .. ".")
		play_sound_with_parameters(actor, SOUND_KIND.HEALTH_RELATED, SOUND_HEALTH_RELATED_MODE.WOUNDED, true)
		return
	end

	-- Moderate Fear (Extra)

	if psy_health < 0.3 then
		-- If psy health is critically low, play blacking out sound to alert player.
		log("Playing fear-related blacking out extra sound with psy health " ..
			psy_health .. " at fear factor " .. fear_factor .. ".")
		play_extra_sound_with_parameters(actor, SOUND_KIND.PSY_RELATED, SOUND_PSY_RELATED_MODE.BLACKING_OUT)
	elseif psy_health < 0.75 and math.random() < 0.35 then
		-- If psy health is lowered, play hallucinations with a chance.
		log("Playing fear-related hallucinations extra sound with psy health " ..
			psy_health .. " at fear factor " .. fear_factor .. ".")
		play_extra_sound_with_parameters(actor, SOUND_KIND.PSY_RELATED, SOUND_PSY_RELATED_MODE.HALLUCINATING)
	end

	-- Low Fear (Sweetener)

	if fear_factor > 0.5 and math.random() < 0.25 then
		-- High distress, play fear sweetener.
		log("Playing high fear sweetener sound with factor " ..
			fear_factor .. " and random index.")
		play_sound_sweetener_with_parameters(actor, SOUND_KIND.REGULAR, SOUND_REGULAR_MODE.SWEETENER)
		return
	end

	-- High Fear

	if fear_factor > 0.85 or (time_since_last_hit < opt.hit_distress_cooldown and last_actor_hit_kind == HIT_KIND.PSYCHIC) then
		-- If fear is very high or last hit was psychic, switch to extreme distress for panicked breathing.
		play_sound_with_parameters(actor, SOUND_KIND.REGULAR, SOUND_REGULAR_MODE.DISTRESSED, true)
		log("Playing high fear breathing sound with factor " ..
			fear_factor .. " and time since last hit " .. time_since_last_hit .. ".")
		return
	end

	if time_since_last_hit < opt.hit_distress_cooldown and last_actor_hit_kind == HIT_KIND.PHYSICAL then
		-- If last hit was physical, switch to distress for panicked breathing.
		play_sound_with_parameters(actor, SOUND_KIND.REGULAR, SOUND_REGULAR_MODE.TERRIFIED, true)
		log("Playing high fear breathing sound for physical hit with time since last hit " .. time_since_last_hit .. ".")
		return
	end

	-- Stamina

	if stamina < 0.35 then
		-- If player has low stamina, switch to exhausted breathing.
		play_sound_with_parameters(actor, SOUND_KIND.STAMINA_RELATED, SOUND_STAMINA_RELATED_MODE.ACTIVE, true)
		log("Playing stamina-related exhausted breathing sound with low stamina at " ..
			stamina .. " and last actor speed time " .. last_actor_speed_time .. ".")
		return
	end

	if last_actor_speed_time > 2.0 then
		-- If player has been running for a short while, switch to active breathing.
		play_sound_with_parameters(actor, SOUND_KIND.STAMINA_RELATED, SOUND_STAMINA_RELATED_MODE.ACTIVE, true)
		log("Playing stamina-related active breathing sound with last actor speed time " .. last_actor_speed_time .. ".")
		return
	end

	-- Low Fear

	if fear_factor > 0.3 then
		-- If fear is moderate, switch to moderate distress for elevated breathing.
		play_sound_with_parameters(actor, SOUND_KIND.REGULAR, SOUND_REGULAR_MODE.ANXIOUS, true)
		log("Playing medium fear factor breathing sound with factor " .. fear_factor .. ".")
		return
	end

	-- Weather

	local weather_kind = get_weather_kind()

	if (not get_is_masked()) and (not get_is_in_safe_space()) and get_is_raining() and (math.random() < 0.03) then
		-- If it's raining or storming, play rain-related sweeteners.
		play_sound_sweetener_with_parameters(actor, SOUND_KIND.WEATHER_RAIN, SOUND_WEATHER_RAIN_MODE.SWEETENER)
		log("Playing rain-related sweetener sound with weather " .. weather_kind .. ".")
		return
	end

	-- Regular

	play_sound_with_parameters(actor, SOUND_KIND.REGULAR, SOUND_REGULAR_MODE.REGULAR, false)
	log("Playing regular breathing sound.")
end

-- Sound Playback

function play_sound_with_parameters(actor, kind, mode, should_reside)
	local index = get_sound_index(kind, mode)
	local pause_factor = get_pause_factor(kind, mode)
	local path = sound_path_from_parameters(kind, mode, index)

	sound_object_ref = sound_object(path)
	sound_object_ref:play(actor, 0, sound_object.s2d)
	sound_object_ref.volume = sound_volume(kind, mode)
	sound_object_ref.frequency = sound_frequency(kind, mode)

	local duration = sound_object_ref:length() or 1000
	suspend_next_breathing(duration * pause_factor)

	if should_reside then
		register_residual_sound(kind, mode, pause_factor)
	end
end

function play_sound_sweetener_with_parameters(actor, kind, mode)
	local index = get_sound_index(kind, mode)
	local pause_factor = get_pause_factor(kind, mode)
	local path = sound_path_from_parameters(kind, mode, index)

	sound_object_ref = sound_object(path)
	sound_object_ref:play(actor, 0, sound_object.s2d)
	sound_object_ref.volume = sound_volume(kind, mode)
	sound_object_ref.frequency = sound_frequency(kind, mode)

	local duration = sound_object_ref:length() or 1000
	suspend_next_breathing(duration * pause_factor)
end

function play_extra_sound_with_parameters(actor, kind, mode)
	if extra_sound_object_ref and extra_sound_object_ref:playing() then
		return
	end

	local index = get_sound_index(kind, mode)
	local path = sound_path_from_parameters(kind, mode, index, true)

	extra_sound_object_ref = sound_object(path)
	extra_sound_object_ref:play(actor, 0, sound_object.s2d)
	extra_sound_object_ref.volume = opt.extra_sound_volume
	extra_sound_object_ref.frequency = sound_frequency(kind)
end

-- Sound Suspension

function stop_and_suspend_breathing(cooldown, reason)
	suspend_next_breathing(cooldown, reason)

	if sound_object_ref then
		sound_object_ref:stop()
	end
end

function suspend_next_breathing(cooldown, reason)
	local current_time = time_global()

	if reason and reason == SOUND_SUSPENSION_REASON.ACTION then
		sound_action_cooldown_time = current_time + cooldown
	else
		sound_cooldown_time = current_time + cooldown
	end
end

function on_actor_hit(hit_kind)
	last_actor_hit_time = time_global()
	last_actor_hit_kind = hit_kind
end

-- Sound Residuality

function register_residual_sound(kind, mode, pause_factor)
	sound_residual_cooldown_by_kind[kind] = {
		mode = mode,
		pause_factor = pause_factor,
		time = time_global() + opt.residuality_time
	}
end

-- Sound Utilities

function sound_path_from_parameters(kind, mode, index, disable_mask_prefixing)
	local sound_name

	if mode ~= nil then
		sound_name = kind .. "_" .. mode .. "_" .. index
	else
		sound_name = kind .. "_" .. index
	end

	if (not disable_mask_prefixing) and get_is_masked() then
		sound_name = "m_" .. sound_name
	end

	return "actor\\" .. sound_name
end

-- Sound Metadata

function sound_volume(kind, mode)
	local volume = opt.breathing_sound_volume

	if kind == SOUND_KIND.FEAR_SWEETENER or kind == SOUND_KIND.WEATHER_RAIN then
		volume = opt.speaking_sound_volume
	end

	local jitter = random_float(-opt.breathing_sound_volume_jitter, opt.breathing_sound_volume_jitter)
	volume = volume + jitter

	if get_is_masked() then
		volume = volume * opt.masked_breathing_sound_coeff
	end

	return volume
end

function sound_frequency(kind, mode)
	return 1 + random_float(-opt.breathing_sound_pitch_jitter, opt.breathing_sound_pitch_jitter)
end

-- Fear Factor

function calculate_fear_factor()
	local time = time_global()
	local is_night = get_is_night()
	local is_underground = get_is_underground()
	local is_in_combat = get_is_in_combat()
	local is_surge = get_is_surge()
	local is_in_safe_space = get_is_in_safe_space()
	local psy_health = get_psy_health()
	local nearby_threats = get_number_of_nearby_threats()
	local number_of_hostile_npcs = nearby_threats.npcs
	local number_of_monsters = nearby_threats.monsters
	local has_been_hit = time < last_actor_hit_time + opt.hit_distress_cooldown

	local fear_value = 0

	fear_value = fear_value + clamp((1 / psy_health - 1) * 6, 0, 7)

	if has_been_hit then
		-- Add fear value based on time since last hit.
		local hit_decay = 1 - clamp((time - last_actor_hit_time) / opt.hit_distress_cooldown, 0, 1)
		fear_value = fear_value + 10 * hit_decay
	end

	if is_in_combat then
		fear_value = fear_value + 1
		fear_value = fear_value + clamp(number_of_hostile_npcs, 0, 4) / 4
		fear_value = fear_value + clamp(number_of_monsters, 0, 4)
	end

	if is_night then
		fear_value = fear_value + 1
	end

	if is_underground then
		fear_value = fear_value + 2
	end

	if is_surge and not is_underground then
		fear_value = fear_value + 2
	end

	if is_in_safe_space and not is_underground then
		fear_value = fear_value / 2
	end

	local fear_factor = clamp(fear_value / 10, 0, 1)

	-- log("Calculated aggregate player fear factor: " ..
	-- 	tostring(fear_factor) ..
	-- 	" (from value " ..
	-- 	fear_value ..
	-- 	") with factors (hit: " .. tostring(has_been_hit) .. ", in combat: " ..
	-- 	tostring(is_in_combat) .. ", night: " .. tostring(is_night) .. ", underground: " ..
	-- 	tostring(is_underground) ..
	-- 	", surge: " .. tostring(is_surge) .. ", safe space: " .. tostring(is_in_safe_space) ..
	-- 	", psy health: " ..
	-- 	tostring(psy_health) ..
	-- 	", nearby hostiles: " ..
	-- 	tostring(number_of_hostile_npcs) .. ", nearby monsters: " .. tostring(number_of_monsters) .. ").")

	fear_factor = math.max(fear_factor, (last_actor_fear * 0.7 + fear_factor * 0.3))
	last_actor_fear = fear_factor

	return fear_factor
end

-- Conditions

function get_is_surge()
	return xr_conditions.surge_started()
end

function get_is_night()
	return level.get_time_hours() < 4 or level.get_time_hours() > 20
end

function get_is_underground()
	local level_name = level.name()
	return UNDERGROUND_LEVELS[level_name] or false
end

function get_is_in_safe_space()
	return GetEvent("current_safe_cover")
end

function get_is_in_combat()
	if not AGDD_voiced_actor then
		return false
	end

	return AGDD_voiced_actor.is_actor_in_combat() or false
end

function get_psy_health()
	if arszi_psy then
		return arszi_psy.get_psy_health()
	end

	return db.actor:psy_health()
end

function get_weather_kind()
	local weather_manager = level_weathers.get_weather_manager()
	local weather_kind = weather_manager:get_curr_weather()

	return weather_kind
end

function get_is_raining()
	local weather_kind = get_weather_kind()
	local is_rainy_weather = weather_kind == WEATHER_KIND.RAINING or weather_kind == WEATHER_KIND.STORM

	return is_rainy_weather and level.rain_factor() > 0.05
end

function get_is_masked()
	return actor_effects.is_respi_on()
end

function get_number_of_nearby_threats()
	local max_radius = opt.fear_factor_npc_detection_radius
	local number_of_hostile_npcs = 0
	local number_of_monsters = 0

	level.iterate_nearest(db.actor:position(), max_radius, function(obj)
		if IsMonster(obj) and obj:alive() then
			number_of_monsters = number_of_monsters + 1
		end

		if IsStalker(obj) and obj:alive() and obj:relation(db.actor) == game_object.enemy then
			number_of_hostile_npcs = number_of_hostile_npcs + 1
		end
	end)

	return { npcs = number_of_hostile_npcs, monsters = number_of_monsters }
end

-- Cooldowns

function cooldown_for_item_use(section)
	local kind = ini_sys:r_string_ex(section, "kind")

	if string.match(section, "cig") then
		kind = "i_tobacco"
	elseif string.match(section, "bandage") then
		kind = "i_bandage"
	end

	local cooldown = ITEM_USE_COOLDOWN_BY_KIND[kind] or opt.item_use_cooldown
	return cooldown
end

-- Hooks

function hook_functions()
	actor_effects.Update_Breathing = update_breathing
	actor_effects.play_sound_breath_mask = function() end
	actor_effects.play_sound_breath = function() end

	-- Item Use Integration via Actor Effects

	local original_actor_on_item_before_use = itms_manager.actor_on_item_before_use

	function itms_manager.actor_on_item_before_use(obj, flags)
		original_actor_on_item_before_use(obj, flags)

		local section = obj:section()
		local cooldown = cooldown_for_item_use(section)

		log("Player used item '" ..
			section .. "' (via items manager on item before use) with cooldown " .. cooldown .. "ms.")
		suspend_next_breathing(cooldown, SOUND_SUSPENSION_REASON.ACTION)
	end
end

function actor_on_before_hit(target_hit, target_bone_id, target_flags)
	if
		target_hit.type == hit.fire_wound or
		target_hit.type == hit.wound or
		target_hit.type == hit.wound_2 or
		target_hit.type == hit.strike or
		target_hit.type == hit.explosion
	then
		log("Registered physical actor hit of type '" .. target_hit.type .. "', updating actor hit cooldown.")
		on_actor_hit(HIT_KIND.PHYSICAL)
		return
	end

	if target_hit.type == hit.telepatic then
		log("Registered psychic actor hit of type '" .. target_hit.type .. "', updating actor hit cooldown.")
		on_actor_hit(HIT_KIND.PSYCHIC)
		return
	end
end

function actor_on_equipment_change(obj)
	local section = obj:section()
	local cooldown = cooldown_for_item_use(section)

	log("Player used item '" .. section .. "' (via actor_on_equipment_change) with cooldown " .. cooldown .. "ms.")
	suspend_next_breathing(cooldown, SOUND_SUSPENSION_REASON.ACTION)
end

function on_game_start()
	RegisterScriptCallback("actor_on_before_hit", actor_on_before_hit)
	RegisterScriptCallback("actor_item_to_slot", actor_on_equipment_change)
	RegisterScriptCallback("actor_item_to_ruck", actor_on_equipment_change)
end

-- Init

init_options()
hook_functions()

-- Utility

function table.has_value(tab, val)
	for _, value in ipairs(tab) do
		if value == val then
			return true
		end
	end

	return false
end

function log(message)
	if not opt.debug_mode then
		return
	end

	printf("SAB - " .. message)
end
